### ISSUE TITLE
i dont want to be anoying sry, **but**

### ISSUE THREAD

**Issue by Tiffycake** [Sefiraat/Simple-Storage#11]
i have searched all nether biomes (bc its quartz) then i searched end biomes and found nothing ?
either its broken or i am just bad at searching plz at least give me a hint

Context: cant find crystall clear quartz

**Comment by Sefiraat** [comment]
This really isn’t a bug. To be sure I tested before replying to your previous issue. If you search this GitHub repo for quartz or clear quartz you will find a page that lists the biomes. It is meant to be found though :)

**Comment by Tiffycake** [comment]
wait but in the wiki it just says unknown location

**Comment by Sefiraat** [comment]
Yeah but you can check my exact code if you like, in my view that’s still you working to find the answer. You could also ask on the discord :)

**Comment by Tiffycake** [comment]
oh okok thanks u can close the issue now (love ur plugin btw)
