### ISSUE TITLE
BLOCK_CELL_BASIC

### ISSUE THREAD

**Issue by jsupa** [Sefiraat/Simple-Storage#22]
## Description (Required)
my simple storage plugin dosent work

## Steps to reproduce the Issue (Required)
idk :D 

## Expected behavior (Required)
Item "BLOCK_CELL_BASIC" from SimpleStorage vDEV - 10 (git ea5e5637) has caused an Error!

## Server Log / Error Report
```
java.lang.LinkageError: loader constraint violation: when resolving method 'me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu me.mrCookieSlime.Slimefun.api.inventory.BlockMenu.addMenuClickHandler(int, me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu$MenuClickHandler)' the class loader org.bukkit.plugin.java.PluginClassLoader @1060746b of the current class, io/github/sefiraat/simplestorage/items/chests/AbstractCache, and the class loader org.bukkit.plugin.java.PluginClassLoader @1d7648dd for the method's defining class, me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ChestMenu, have different Class objects for the type me/mrCookieSlime/CSCoreLibPlugin/general/Inventory/ChestMenu$MenuClickHandler used in the signature (io.github.sefiraat.simplestorage.items.chests.AbstractCache is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @1060746b, parent loader java.net.URLClassLoader @2e5d6d97; me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @1d7648dd, parent loader java.net.URLClassLoader @2e5d6d97)

```
![image](https://user-images.githubusercontent.com/74856856/207092946-ba711474-a7ca-4e1b-a97a-099b8bd8b665.png)

## Environment (Required)

 - Minecraft Version: 1.19.2
 - CS-CoreLib Version: 1.6.3
 - Slimefun Version: Slimefun4 - DEV 1035 (git 0b7c6))
 - Plugin Version: Simple-Storage - DEV 10 (git ea5e5)

**Comment by Sefiraat** [comment]
Remove CSCoreLib, it’s not been required for some time now and, in fact, now causes issues. If it’s not the answer then lmk and I’ll reopen the call :)

**Comment by jsupa** [comment]
Oh, yeah, fixed :D thanks
