### ISSUE TITLE
two new ingots wont work with the electric smelteries

### ISSUE THREAD

**Issue by szvenz** [Sefiraat/Simple-Storage#3]
## Description (Required)
CUPRONICKEL and Nickel super allow ingots, don't smelt in electric smelteries. tried both an advanced smeltery  and a regular smeltery. all of the other new allows from simple storage work in their respective smelteries

## Expected behavior (Required)
expected the advanced smelteries to work with these two recopies as well

## Server Log / Error Report

Error Generated: 2021-06-14-01-40

Java Environment:
  Operating System: Linux
  Java Version: 11.0.10

Server Software: Paper
  Build: git-Paper-762 (MC: 1.16.5)
  Minecraft v1.16.5-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vDEV - 936 (git aa5a22cb)
  Caused by: SimpleStorage vDEV - 4 (git 470e7be7)

Installed Addons (15)
  + DankTech 1.2.7
  + ExtraTools DEV - 28 (git 58488a2e)
  + FoxyMachines DEV - 45 (git ce4f8193)
  + SlimefunOreChunks DEV - 13 (git 9f7a2be3)
  + SlimyTreeTaps DEV - 19 (git 69930ef7)
  + FluffyMachines DEV - 84 (git cf78f53a)
  + SimpleUtils DEV - 9 (git 7f454341)
  + SimpleStorage DEV - 4 (git 470e7be7)
  + InfinityExpansion DEV - 114 (git 9d5d3cec)
  + EMC2 DEV - 4 (git b1c851fb)
  + SlimefunWarfare DEV - 41 (git 32f65443)
  + HotbarPets DEV - 37 (git 63b1553e)
  + SlimefunLuckyBlocks DEV - 35 (git 3b6586d6)
  + ExoticGarden DEV - 76 (git d148a362)
  + DynaTech DEV - 129 (git a1808147)

Installed Plugins (52):
  + PlugMan 2.1.7
  + NoMobGriefing 0.2.4
  + RideMe 1.1
  + ViaVersion 4.0.0
  - Geyser-Spigot 1.2.0-SNAPSHOT
  + TreeFeller 1.13.5
  + LuckPerms 5.1.26
  + OpenInv 4.0.8
  + Multiverse-Core 4.1.1-SNAPSHOT-b777
  + ProtocolLib 4.5.1
  + floodgate-bukkit 1.0-SNAPSHOT
  + Vault 1.7.2-b107
  + PerWorldInventory 2.3.2
  + MaintenanceSpigot 3.0.3
  + PetMaster 1.12.1
  - dynmap 3.1-457
  + Essentials 2.17.2.130
  + MineableSpawners 3.0.11
  + Carz 7.2
  + Citizens 2.0.27-SNAPSHOT (build 2165)
  + Sentinel 2.2.0-SNAPSHOT (build 373)
  + FastAsyncWorldEdit 1.16-651;4d77771
  + EssentialsChat 2.17.2.130
  + SuperVanish 6.1.5
  + WorldGuard 7.0.2-SNAPSHOT;bf2593e
  + EssentialsAntiBuild 2.17.2.130
  + EssentialsSpawn 2.17.2.130
  + CitizensGUI 1.9
  + DiscordSRV 1.20.0
  + QuickShop 4.0.5.9
  + UltimateChairs 1.3.1
  + DankTech 1.2.7
  + LockettePro 2.10.10
  + Slimefun DEV - 936 (git aa5a22cb)
  + ExtraTools DEV - 28 (git 58488a2e)
  + FoxyMachines DEV - 45 (git ce4f8193)
  + SlimefunOreChunks DEV - 13 (git 9f7a2be3)
  + SlimyTreeTaps DEV - 19 (git 69930ef7)
  + FluffyMachines DEV - 84 (git cf78f53a)
  + SimpleUtils DEV - 9 (git 7f454341)
  + SimpleStorage DEV - 4 (git 470e7be7)
  + InfinityExpansion DEV - 114 (git 9d5d3cec)
  + EMC2 DEV - 4 (git b1c851fb)
  + SlimefunWarfare DEV - 41 (git 32f65443)
  + HotbarPets DEV - 37 (git 63b1553e)
  + SlimefunLuckyBlocks DEV - 35 (git 3b6586d6)
  + ExoticGarden DEV - 76 (git d148a362)
  + DynaTech DEV - 129 (git a1808147)
  + CoreProtect 2.18.2
  + Plan 5.0 build 415
  + MobTransporter 2.4
  + KeepChunks 1.6.7

Block Info:
  World: world
  X: -1843
  Y: 55
  Z: 228
  Material: AIR
  Block Data: org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData
  State: org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockState

Ticker-Info:
  Type: Synchronized

Slimefun Data:
  ID: BLOCK_CELL_BASIC
  Inventory: true
  Data: {"simple-chest-id":"1","id":"BLOCK_CELL_BASIC"}

Stacktrace:

java.lang.NullPointerException
	at io.github.sefiraat.simplestorage.items.chests.SimpleInventoryCache.updateItems(SimpleInventoryCache.java:39)
	at io.github.sefiraat.simplestorage.items.chests.SimpleInventoryCache.process(SimpleInventoryCache.java:85)
	at io.github.sefiraat.simplestorage.items.chests.SimpleChest$1.tick(SimpleChest.java:53)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:188)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:169)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427)
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
	at java.base/java.lang.Thread.run(Thread.java:834)

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - Plugin Version: 

Paper git-Paper-762 (MC: 1.16.5)
Slimefun DEV - 936 (git aa5a22cb)
Metrics-Module #25
Java 11
Installed Addons: (15)
ExtraTools vDEV - 28 (git 58488a2e)
FoxyMachines vDEV - 45 (git ce4f8193)
SlimefunOreChunks vDEV - 13 (git 9f7a2be3)
SlimefunWarfare vDEV - 41 (git 32f65443)
HotbarPets vDEV - 37 (git 63b1553e)
DynaTech vDEV - 129 (git a1808147)
SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
ExoticGarden vDEV - 76 (git d148a362)
InfinityExpansion vDEV - 114 (git 9d5d3cec)
SimpleUtils vDEV - 9 (git 7f454341)
EMC2 vDEV - 4 (git b1c851fb)
SlimyTreeTaps vDEV - 19 (git 69930ef7)
DankTech v1.2.7
FluffyMachines vDEV - 84 (git cf78f53a)
SimpleStorage vDEV - 4 (git 470e7be7)

**Comment by Sefiraat** [comment]
Hi Szvenz, 
Ill look into the electric smelteries.

The error log you have attached indicates an issue with the inventory cells though, not an issue with the smeltery. What error is this and how did you get it?

**Comment by Sefiraat** [comment]
The next auto-update of Simple Storage will fix these two reipces to allow them to work in the electric smeltery.

I wont close this call for now as the error report is a bit concerning. Please could you elaborate on how you got that error?

**Comment by szvenz** [comment]
got the update and i can confirm they work in the electric smeltery.

im not sure how i got that error report, i noticed it when i checked while trouble shooting emc2. i do remember having an out of memory restart. but thats not too uncommon while im messing with slimefun.

also, just noticed that at least the iron chest doesn't craft in an enhanced autocrafter

**Comment by Sefiraat** [comment]
I have just quickly tested this and It crafted for me, for now I'll close this issue and If you could 100% confirm that you cannot auto craft with it, can you raise a new issue to keep the topics separated.
