### ISSUE TITLE
Network chest recipe invalid

### ISSUE THREAD

**Issue by pHI10S0PH3RKING** [Sefiraat/Simple-Storage#5]
## Description (Required)

Tried to make the network chest as displayed in the guide but enhanced crafting table and slimetinker workbench both report invalid recipe. 
## Steps to reproduce the Issue (Required)

place 6 combination plates a diamond chest and a communication block in the enhanced crafting table or slimetinker workbench as per crafting recipe in the slimefun guide and attempt to craft.
## Expected behavior (Required)

I expected the crafting recipe to produce a network chest
## Server Log / Error Report

no logs i can access because im a player on the server where it happened (tantrum) 
![image](https://user-images.githubusercontent.com/85084869/126577082-315eda6e-082c-400e-9eb2-38047ca1220e.png)
![image](https://user-images.githubusercontent.com/85084869/126577089-c60bac66-2f72-4117-ac12-3b59233f7243.png)
![image](https://user-images.githubusercontent.com/85084869/126577095-8672169a-5905-4be8-8a4a-70a9b8dfa097.png)

## Environment (Required)

![image](https://user-images.githubusercontent.com/85084869/126577042-36ae1e05-d4e3-42b5-897b-7bc7dd537052.png)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - Plugin Version:

**Comment by pHI10S0PH3RKING** [comment]
Ok apparently its my fault i didnt see the display panel because its nearly invisible so a diffrent icon might be in order

**Comment by Sefiraat** [comment]
Something that has been raised in the past yeah, it was worse before as well. Ill try to think on a good subsitute :)

**Comment by pHI10S0PH3RKING** [comment]
even just changing it to black would improve visibility
