### ISSUE TITLE
Zamak can be used as netherite in smithing table

### ISSUE THREAD

**Issue by gecko10000** [Sefiraat/Simple-Storage#8]
## Description (Required)
Zamak can be used as a netherite ingot in smithing tables, which obviously is not intended and becomes a very easy way to obtain it.

## Steps to reproduce the Issue (Required)
![2021-09-12_22 34 51](https://user-images.githubusercontent.com/60494179/133029645-0efc4fee-0c2f-4c53-b51a-9cf10226f21e.png)
![2021-09-12_22 34 49](https://user-images.githubusercontent.com/60494179/133029662-d1500314-748e-4fee-b713-8879a0be4912.png)

## Expected behavior (Required)
The recipe should be invalidated with a Slimefun item.

## Environment (Required)
```
[05:40:55 INFO]: This Server uses the following setup of Slimefun:
Purpur git-Purpur-1385 (MC: 1.17.1)
Slimefun DEV - 968 (git 79c6c139)
Metrics-Module #28
Java 16

Installed Addons: (16)
  DyedBackpacks vDEV - 17 (git 8b329e96)
  ExtraTools vDEV - 29 (git 83f6db7f)
  SoundMuffler vDEV - 22 (git 37411b6c)
  EcoPower vDEV - 5 (git 5c1ecd68)
  ExoticGarden vDEV - 77 (git a2c4b6d3)
  InfinityExpansion vDEV - 123 (git f5f22167)
  SFCalc vDEV - 34 (git 60f3c45d)
  ExtraHeads vDEV - 22 (git 35688aa3)
  SoulJars vDEV - 23 (git b8358a1f)
  MobCapturer vDEV - 17 (git c21b00a5)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  ColoredEnderChests vDEV - 23 (git 4d041832)
  SimpleStorage vDEV - 7 (git ef9035b3)
  FluffyMachines vDEV - 90 (git b36089e8)
```

**Comment by gecko10000** [comment]
I assume this is more of an issue with base Slimefun items, but not sure where else to put this as no other addon has easily obtainable Slimefun item netherite ingots.

**Comment by Sefiraat** [comment]
Fixed in the above mentioned PR :) Thanks for the report!
